-- ============================================================================
-- E-Bookstore — PostgreSQL schema
-- Source of truth: docs/data-model/02-data-model.md
-- Must stay consistent with the JPA entities (spring.jpa.hibernate.ddl-auto=validate).
--
-- Primary keys: BIGINT GENERATED BY DEFAULT AS IDENTITY (DM-09) — matches
-- @GeneratedValue(strategy = GenerationType.IDENTITY).
-- Monetary columns: NUMERIC(10,2) — mapped to BigDecimal.
-- Timestamps: TIMESTAMP WITH TIME ZONE — mapped to OffsetDateTime.
--
-- This script is idempotent (IF NOT EXISTS) so it is safe to re-run.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- users
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name     VARCHAR(255)             NOT NULL,
    email         VARCHAR(255)             NOT NULL UNIQUE,
    password_hash VARCHAR(255)             NOT NULL,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- categories
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);

-- ---------------------------------------------------------------------------
-- brands (publisher / brand grouping — DM-01)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS brands (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

-- ---------------------------------------------------------------------------
-- books
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS books (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title                  VARCHAR(500)             NOT NULL,
    author                 VARCHAR(255)             NOT NULL,
    isbn                   VARCHAR(20)              UNIQUE,
    description            TEXT,
    price                  NUMERIC(10,2)            NOT NULL CHECK (price >= 0),
    stock_quantity         INTEGER                  NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    delivery_estimate_days INTEGER                  NOT NULL CHECK (delivery_estimate_days > 0),
    category_id            BIGINT                   NOT NULL REFERENCES categories(id) ON DELETE RESTRICT,
    brand_id               BIGINT                   REFERENCES brands(id) ON DELETE SET NULL,
    created_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_books_category_id ON books(category_id);
CREATE INDEX IF NOT EXISTS idx_books_brand_id    ON books(brand_id);

-- ---------------------------------------------------------------------------
-- addresses
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS addresses (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT                   NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    recipient_name VARCHAR(255)             NOT NULL,
    street_line1   VARCHAR(255)             NOT NULL,
    street_line2   VARCHAR(255),
    city           VARCHAR(100)             NOT NULL,
    state          VARCHAR(100)             NOT NULL,
    postal_code    VARCHAR(20)              NOT NULL,
    country        VARCHAR(100)             NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_addresses_user_id ON addresses(user_id);

-- ---------------------------------------------------------------------------
-- carts (one reusable cart per customer — DM-06)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS carts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT                   NOT NULL UNIQUE REFERENCES users(id) ON DELETE RESTRICT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

-- ---------------------------------------------------------------------------
-- cart_items (unique per book per cart — DM-07)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS cart_items (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id  BIGINT  NOT NULL REFERENCES carts(id) ON DELETE CASCADE,
    book_id  BIGINT  NOT NULL REFERENCES books(id) ON DELETE RESTRICT,
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    CONSTRAINT uq_cart_items_cart_book UNIQUE (cart_id, book_id)
);

CREATE INDEX IF NOT EXISTS idx_cart_items_cart_id ON cart_items(cart_id);

-- ---------------------------------------------------------------------------
-- orders (CONFIRMED/CANCELLED only — DM-08; address snapshot — DM-03;
--         no separate payments table — DM-02)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS orders (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                     BIGINT                   NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
    status                      VARCHAR(20)              NOT NULL DEFAULT 'CONFIRMED',
    total_amount                NUMERIC(10,2)            NOT NULL CHECK (total_amount >= 0),
    payment_method              VARCHAR(20)              NOT NULL,
    simulated_payment_reference VARCHAR(100),
    address_id                  BIGINT                   REFERENCES addresses(id) ON DELETE SET NULL,
    snap_recipient              VARCHAR(255)             NOT NULL,
    snap_street_line1           VARCHAR(255)             NOT NULL,
    snap_street_line2           VARCHAR(255),
    snap_city                   VARCHAR(100)             NOT NULL,
    snap_state                  VARCHAR(100)             NOT NULL,
    snap_postal_code            VARCHAR(20)              NOT NULL,
    snap_country                VARCHAR(100)             NOT NULL,
    created_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_orders_user_created ON orders(user_id, created_at);

-- ---------------------------------------------------------------------------
-- order_items (unit price locked at purchase — BR-06)
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS order_items (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT        NOT NULL REFERENCES orders(id) ON DELETE RESTRICT,
    book_id    BIGINT        NOT NULL REFERENCES books(id)  ON DELETE RESTRICT,
    quantity   INTEGER       NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(10,2) NOT NULL CHECK (unit_price >= 0)
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
